# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_init.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_init.ipynb 3
def foo(): pass
